language: java

#this will reuse maven dependencies so it doesn't redownload everytime
cache:
  directories:
    - $HOME/.m2

script:
  - ./installExtraJars.sh
  - ./mvnw clean install -DskipTests
  - ./mvnw test
